name: HuntailHunters
version: 1.0
author: FennekFoxy
main: com.fennekfoxy.huntailhunters.HuntailHunters
api-version: 1.16
commands:
  huntailhunters:
    description: Huntail Hunters event
    usage: /huntailhunters <subcommand>
    aliases: hh
permissions:
  huntailhunters:
    description: Allowes use of the /huntailhunters command
    default: true
    children:
      huntailhunters.join: true
      huntailhunters.stats: true
